-- Script Completo para Supabase - Boleiros de Cristo
-- Execute no SQL Editor do Supabase

create table if not exists public.grupos (
  id uuid primary key default gen_random_uuid(),
  nome text not null,
  slug text not null unique,
  logo_url text,
  created_at timestamptz default now()
);

create table if not exists public.usuarios_grupo (
  id uuid primary key default gen_random_uuid(),
  grupo_id uuid not null references public.grupos(id) on delete cascade,
  email text not null,
  user_id uuid references auth.users(id) on delete set null,
  role text not null default 'admin',
  status text not null default 'approved',
  created_at timestamptz default now(),
  constraint unique_grupo_email unique (grupo_id, email)
);

create table if not exists public.jogadores (
  id bigint generated by default as identity primary key,
  grupo_id uuid not null references public.grupos(id) on delete cascade,
  nome text not null,
  categoria numeric(2,1) not null default 3.0,
  goleiro boolean not null default false,
  menina boolean not null default false,
  ativo boolean not null default true,
  created_at timestamptz default now()
);

alter table if exists public.usuarios_grupo add column if not exists status text default 'approved';

create index if not exists idx_jogadores_grupo on public.jogadores(grupo_id);
create index if not exists idx_usuarios_grupo_email on public.usuarios_grupo(lower(email));
create index if not exists idx_grupos_slug on public.grupos(slug);
-- Regra: 1 owner por grupo (owner tambem conta no limite de 5 do trigger)
create unique index if not exists unique_owner_por_grupo on public.usuarios_grupo(grupo_id) where role = 'owner';

create or replace function public.check_limite_usuarios_grupo()
returns trigger as $$
begin
  if (select count(*) from public.usuarios_grupo where grupo_id = NEW.grupo_id) >= 5 then
    raise exception 'Limite maximo de 5 administradores por grupo atingido.';
  end if;
  NEW.email := lower(trim(NEW.email));
  return NEW;
end;
$$ language plpgsql;

drop trigger if exists trg_check_limite_usuarios_grupo on public.usuarios_grupo;

create trigger trg_check_limite_usuarios_grupo
before insert on public.usuarios_grupo
for each row execute function public.check_limite_usuarios_grupo();

create or replace function public.check_limite_jogadores()
returns trigger as $$
begin
  if (select count(*) from public.jogadores where grupo_id = NEW.grupo_id) >= 150 then
    raise exception 'Limite maximo de 150 jogadores por grupo atingido.';
  end if;
  return NEW;
end;
$$ language plpgsql;

drop trigger if exists trg_check_limite_jogadores on public.jogadores;

create trigger trg_check_limite_jogadores
before insert on public.jogadores
for each row execute function public.check_limite_jogadores();

-- Auto-link user_id quando novo usuario cria conta no Supabase Auth
create or replace function public.link_user_to_group()
returns trigger as $$
begin
  update public.usuarios_grupo
  set user_id = NEW.id
  where email = lower(NEW.email)
    and user_id is null;
  return NEW;
end;
$$ language plpgsql security definer;

drop trigger if exists trg_link_auth_user on auth.users;

create trigger trg_link_auth_user
after insert on auth.users
for each row execute function public.link_user_to_group();

drop trigger if exists trg_owner_auto_approved on public.usuarios_grupo;

alter table public.grupos enable row level security;
alter table public.usuarios_grupo enable row level security;
alter table public.jogadores enable row level security;

create or replace function public.is_admin_do_grupo(grupo_uuid uuid)
returns boolean as $$
begin
  return exists (
    select 1 from public.usuarios_grupo
    where grupo_id = grupo_uuid
      and user_id = auth.uid()
      and status = 'approved'
  );
end;
$$ language plpgsql security definer;

create or replace function public.set_owner_approved()
returns trigger as $$
begin
  if (NEW.role = 'owner') then
    NEW.status := 'approved';
  end if;
  return NEW;
end;
$$ language plpgsql security definer;

create trigger trg_owner_auto_approved
before insert on public.usuarios_grupo
for each row execute function public.set_owner_approved();

drop policy if exists "Grupos visiveis publicamente" on public.grupos;
drop policy if exists "Usuarios autenticados criam grupo" on public.grupos;
drop policy if exists "Admins atualizam grupos" on public.grupos;
drop policy if exists "Admins deletam grupos" on public.grupos;
create policy "Grupos visiveis publicamente" on public.grupos for select using (true);
create policy "Usuarios autenticados criam grupo" on public.grupos for insert to authenticated with check (true);
create policy "Admins atualizam grupos" on public.grupos for update to authenticated using (public.is_admin_do_grupo(id));
create policy "Admins deletam grupos" on public.grupos for delete to authenticated using (public.is_admin_do_grupo(id));

drop policy if exists "Membros veem admins" on public.usuarios_grupo;
drop policy if exists "Usuarios veem proprio vinculo" on public.usuarios_grupo;
drop policy if exists "Usuarios criam proprio vinculo" on public.usuarios_grupo;
drop policy if exists "Admins aprovam pending" on public.usuarios_grupo;
drop policy if exists "Admins removem admins" on public.usuarios_grupo;
create policy "Membros veem admins" on public.usuarios_grupo for select to authenticated using (public.is_admin_do_grupo(grupo_id));
create policy "Usuarios veem proprio vinculo" on public.usuarios_grupo for select to authenticated using (user_id = auth.uid());
create policy "Usuarios criam proprio vinculo" on public.usuarios_grupo for insert to authenticated with check (user_id = auth.uid());
create policy "Admins aprovam pending" on public.usuarios_grupo for update to authenticated using (public.is_admin_do_grupo(grupo_id)) with check (public.is_admin_do_grupo(grupo_id));
create policy "Admins removem admins" on public.usuarios_grupo for delete to authenticated using (public.is_admin_do_grupo(grupo_id));

drop policy if exists "Jogadores visiveis publicamente" on public.jogadores;
drop policy if exists "Admins inserem jogadores" on public.jogadores;
drop policy if exists "Admins atualizam jogadores" on public.jogadores;
drop policy if exists "Admins deletam jogadores" on public.jogadores;
create policy "Jogadores visiveis publicamente" on public.jogadores for select using (ativo = true);
create policy "Admins inserem jogadores" on public.jogadores for insert to authenticated with check (public.is_admin_do_grupo(grupo_id));
create policy "Admins atualizam jogadores" on public.jogadores for update to authenticated using (public.is_admin_do_grupo(grupo_id));
create policy "Admins deletam jogadores" on public.jogadores for delete to authenticated using (public.is_admin_do_grupo(grupo_id));

do $$
declare v_grupo_id uuid;
begin
  insert into public.grupos (nome, slug, logo_url) values ('Boleiros de Cristo', 'boleiros-de-cristo', 'logo-boleiros.png') on conflict (slug) do nothing returning id into v_grupo_id;
  if v_grupo_id is null then select id into v_grupo_id from public.grupos where slug = 'boleiros-de-cristo'; end if;
  -- insert do owner apenas se ainda nao existir (evita disparar trigger de limite no ON CONFLICT)
  if not exists (select 1 from public.usuarios_grupo where grupo_id = v_grupo_id and email = 'seu-email@exemplo.com') then
    insert into public.usuarios_grupo (grupo_id, email, role, status) values (v_grupo_id, 'SEU-EMAIL@EXEMPLO.COM', 'owner', 'approved');
  end if;
end;
$$;

-- Seed idempotente: insere apenas jogadores que ainda nao existem (por nome + grupo)
insert into public.jogadores (grupo_id, nome, categoria, goleiro, menina)
select g.id, a.nome, a.categoria, a.goleiro, a.menina from (values
  ('Adeilson', 4, false, false),
  ('Adriel', 3, false, false),
  ('Adryel', 4, false, false),
  ('Alex', 3, false, false),
  ('Alexsander jr', 2.5, false, false),
  ('Andrew', 3, false, false),
  ('André', 3, false, false),
  ('Araújo', 4, false, false),
  ('Arthur', 3, false, false),
  ('Arthur Manoel', 2, false, false),
  ('Azevedo', 4, false, false),
  ('Beto', 4, false, false),
  ('Breno Beto', 3, false, false),
  ('Caio', 3, false, false),
  ('Carlos', 4, false, false),
  ('Carlos Heraldo', 3, false, false),
  ('Daniel Gomes', 3, false, false),
  ('Davi', 1, false, false),
  ('Davi Serra', 4, false, false),
  ('Douglas', 2, false, false),
  ('Eduardo', 4, false, false),
  ('Erick', 4, false, false),
  ('Erick Nunes', 3, true, false),
  ('Felipe', 4, false, false),
  ('Felipe Gomes', 3, false, false),
  ('Felipe Oliveira', 3, true, false),
  ('Fernando (Jr.)', 3, false, false),
  ('Fernando Carlim', 3, false, false),
  ('Fernando Jr.', 3, false, false),
  ('Filipi', 2, false, false),
  ('Frank', 2, true, false),
  ('Gabriel', 4, false, false),
  ('Gabriel Beto', 3, false, false),
  ('Gabriel Hot', 4, false, false),
  ('Gilmar', 3, false, false),
  ('Giovani', 3, false, false),
  ('Guilherme', 4, false, false),
  ('Guilherme Beto', 4, false, false),
  ('Gustavo', 4, false, false),
  ('Heber', 4, false, false),
  ('Heraldo', 3, false, false),
  ('Hugo', 2, false, false),
  ('Hugo Correia', 3, false, false),
  ('Hyuri', 3, false, false),
  ('Igor', 4, false, false),
  ('Jonas', 3, false, false),
  ('Jordan', 3, true, false),
  ('João Gabriel', 2, false, false),
  ('João Nóvoa', 3, false, false),
  ('João Pedro', 3, false, false),
  ('João Poubel', 1, false, false),
  ('João Roberto', 3, false, false),
  ('Júnior', 3, false, false),
  ('Kaio Couto', 3, false, false),
  ('Karina', 1, false, false),
  ('Leandro', 5, false, false),
  ('Leo Muniz', 3, false, false),
  ('Leonardo', 4, false, false),
  ('Levir', 4, false, false),
  ('Lorena', 1, false, false),
  ('Loureiro', 3, true, false),
  ('Lucas Ferreira Conv.', 3, false, false),
  ('Lucas Gabigol', 4, false, false),
  ('Lucas Matheus', 3, false, false),
  ('Lucas Motta', 3, false, false),
  ('Lucas Pereira', 3, false, false),
  ('Lucas Pilão', 3, false, false),
  ('Luis Araújo', 4, false, false),
  ('Luis Felipe', 4, false, false),
  ('Luis Paulo', 4, false, false),
  ('Luiz Guilherme', 3, false, false),
  ('Luy', 4, false, false),
  ('Macena', 3, false, false),
  ('Maicão', 3, false, false),
  ('Marcos Aurélio', 3, false, false),
  ('Marquinhos', 3, false, false),
  ('Matheus', 4, false, false),
  ('Matheus Coelho', 3, false, false),
  ('Matheus Conv', 3, false, false),
  ('Matheus Hot', 2, false, false),
  ('Matheus Nunes', 3.5, false, false),
  ('Matheus Sales', 3, false, false),
  ('Miguel', 2, false, false),
  ('Moraes', 4, false, false),
  ('Moreno', 3, false, false),
  ('Nicholas', 4, false, false),
  ('Nogueira', 4, false, false),
  ('Osni', 4, false, false),
  ('Pablo', 3, false, false),
  ('Paulinho', 2, true, false),
  ('Paulo M.', 4, false, false),
  ('PC', 4, false, false),
  ('Pedrinho', 3, false, false),
  ('Pedro', 3, false, false),
  ('Pedro L', 4, false, false),
  ('Pedro Paulo', 2, false, false),
  ('Popó', 3.5, false, false),
  ('Rafael', 2, false, false),
  ('Rafael Santos', 3, false, false),
  ('Renan', 3, false, false),
  ('Renan Amorim', 2, false, false),
  ('Rhian', 3, false, false),
  ('Rhuann', 3, false, false),
  ('Ricardo', 3, false, false),
  ('Ricardo T.', 4, false, false),
  ('Rodrigo', 4, false, false),
  ('Romulo', 3, false, false),
  ('Ruan', 4, false, false),
  ('Russo', 4, false, false),
  ('Samuel Convidado', 4, false, false),
  ('Samuel Freire', 2, false, false),
  ('Thamires', 1, false, true),
  ('Thamyris', 1, false, true),
  ('Tio Alexandre', 3, false, false),
  ('Vieira', 3, false, false),
  ('Vini', 3, false, false),
  ('Vinicius Henriques', 4, false, false),
  ('Wagner', 4.5, false, false),
  ('Walace', 4, false, false),
  ('Wanderlei', 1, false, false),
  ('Washington', 3, false, false),
  ('Wellington', 3, false, false),
  ('Windsor', 3, false, false),
  ('Yan', 3, false, false),
  ('Yan Goleiro', 3, true, false),
  ('Yuri Felipe', 4, false, false)) as a(nome, categoria, goleiro, menina)
cross join (select id from public.grupos where slug = 'boleiros-de-cristo') g
where not exists (
  select 1 from public.jogadores j where j.grupo_id = g.id and j.nome = a.nome
);

-- Verificacao: select count(*) from jogadores where grupo_id = (select id from grupos where slug = 'boleiros-de-cristo');
